RooflineAI/iree

compiler/src/iree/compiler/Dialect/Flow/IR/FlowOpFolders.cpp
compiler/src/iree/compiler/Dialect/Flow/IR/test/tensor_folding.mlir

Certain cases involve constants who have been converted to resources.
The following change simply ignores these in the folding operation.
One possible future improvement is to perform the slicing at compile
time as we do for the DenseElements, but for now to unblock failing
models this is good enough

fix(TensorSliceOp::fold): ignore DenseResourceElementsAttr

---

compiler/src/iree/compiler/Codegen/Dialect/GPU/TargetUtils/KnownTargets.cpp
compiler/src/iree/compiler/Codegen/SPIRV/VideoCoreConfig.cpp
compiler/src/iree/compiler/Codegen/SPIRV/test/BUILD.bazel
compiler/src/iree/compiler/Codegen/SPIRV/test/CMakeLists.txt
compiler/src/iree/compiler/Codegen/SPIRV/test/config_broadcom_conv.mlir

It seems the best tiling result for the ukernel benchmark
example of 1x16x258x258 with a filter of 256x16x3x3 is around
2.7 GFlops.
The same on the raspberry pi CPU is around 28 GFlops. There is
still a lot of work to be done before the GPU has similar performance
to the CPU variant.

feat(Broadcom): Add initial Conv2d Tiling

---

compiler/src/iree/compiler/Codegen/SPIRV/VideoCoreConfig.cpp

using the literal `1ll` could mean different widths depending on the architecture. Just a small clean up to make it explicit for the template deduction.

refactor(VideoCoreConfig): use explicit casting for literals

---

compiler/src/iree/compiler/Dialect/Util/Analysis/Constant/ConstExpr.cpp
compiler/src/iree/compiler/Dialect/Util/Transforms/test/hoist_into_globals_linalg.mlir

This change fixes the problem where constExprs, which only have a consumer within a nested region, can end up with 0 consumers. This leads to the issue that these constExprs can't get hoisted, as the ConstExprHoistingPolicy will determine them as invalid because they can't have a legal escape if they don't have any consumers. A more detailed description of what happens is in https://github.com/iree-org/iree/issues/18779.

ConstExpr: expand to parents of nested consumers, fixes #18779

---

.gitmodules

Updates `torch-mlir` to point at our roofline fork to to the latest commit of `integrate-torch-mlir-20241122`.

[torch-mlir] roo-91: memory leak fix

---

compiler/src/iree/compiler/Tools/CMakeLists.txt
compiler/src/iree/compiler/Tools/init_mlir_dialects.h
compiler/src/iree/compiler/Tools/init_mlir_passes.h

I found when parsing the outputs of the compiler pipeline and
attempting to elide the constants that there were some dialects and
passes missing from the tool. And when replaying a certain PassManager 
pipeline there were something passes missing form opt.

fix(iree-opt): add missing passes and dialects

---

runtime/src/iree/hal/buffer.c
runtime/src/iree/hal/cts/buffer_mapping_test.h

Fixed buffer access validation and added device-to-device transfer test for HAL buffers.
- Modified `iree_hal_buffer_validate_access` to allow access when either the allowed memory access is set to `IREE_HAL_MEMORY_ACCESS_ANY`
- Added new test case `Transferd2d` to verify device-to-device buffer transfers with allowed access `IREE_HAL_MEMORY_ACCESS_ANY`
- Introduced overload of `AllocateUninitializedBuffer` helper method to support buffer allocation with custom access flags

fix(iree_hal_buffer_validate_access): Buffer access check ignores allowed access ANY

---

compiler/plugins/target/LLVMCPU/LLVMTargetOptions.cpp
compiler/plugins/target/LLVMCPU/LLVMTargetOptions.h
compiler/src/iree/compiler/Codegen/LLVMCPU/LLVMCPUCheckIRBeforeLLVMConversion.cpp
compiler/src/iree/compiler/Codegen/LLVMCPU/test/hal_target_device_attributes.mlir

In order to systemically address `exceeded stack allocation limit` failures for the CPU pipeline, we first need a way of conveying the limit itself to the whole pipeline. Therefore, create a new context-wide attribute, as well as a bound CLI option to replace the one specific to `LLVMCPUCheckIRBeforeLLVMConversionPass`.
A further direction for improvement would be unit-testing all the target properties & corresponding CLI options on the basis of this PR.

refactor(iree): set CPU stack allocation limit as an LLVM target option

---

compiler/plugins/target/LLVMCPU/LLVMTargetOptions.h
compiler/src/iree/compiler/Codegen/LLVMCPU/test/hal_target_device_attributes.mlir

fix(iree): fix default value of CPU stack allocation limit

---

compiler/plugins/target/LLVMCPU/LLVMTargetOptions.cpp
compiler/plugins/target/LLVMCPU/LLVMTargetOptions.h
compiler/plugins/target/LLVMCPU/test/BUILD.bazel
compiler/plugins/target/LLVMCPU/test/CMakeLists.txt
compiler/plugins/target/LLVMCPU/test/hal_target_device_attributes.mlir
compiler/src/iree/compiler/Codegen/LLVMCPU/LLVMCPUCheckIRBeforeLLVMConversion.cpp

- Address formatting issues
- Move the LIT test, register with Bazel & CMake
- Use `PowerOf2ByteSize` for the CLI option, add negative LIT check
- Improve readability in the verification pass

fix(iree): adjust stack allocation patches per upstream review

---

compiler/src/iree/compiler/Dialect/Flow/Transforms/RegionOpUtils.cpp
compiler/src/iree/compiler/DispatchCreation/FormDispatchRegions.cpp
compiler/src/iree/compiler/DispatchCreation/test/BUILD.bazel
compiler/src/iree/compiler/DispatchCreation/test/CMakeLists.txt
compiler/src/iree/compiler/DispatchCreation/test/dispatch_non_fusable.mlir

This fix is necessitated by lack of fusion support for LinalgExt Scan - since
the default LLVMCPU tiling does not respect the fusability of producer ops, nor
the limit for stack-bound allocations, we force this non-fusable "cumulative
reduction"-style operation to be dispatched separately from non-trivial linalg
operations.
Further enhancements should include tiling config fine-tuning for LinalgExt
operations, conscious restrictions of work-group level tiling depending on the
predicted size of stack-bound allocas within a dispatch, and further adoption
of `LinalgFusionOpInterface` for LinalgExt operations that cannot be expressed
through simple reduction iterators. Possible adjustments to the
FormDispatchRegion algorithm itself are noted as TODO items.

fix(iree,cpu): put linalg producers for `iree_linalg_ext.scan` into separate dispatch

---

runtime/src/iree/hal/device.c
runtime/src/iree/hal/device.h
runtime/src/iree/hal/drivers/cuda/cuda_device.c
runtime/src/iree/hal/drivers/hip/hip_device.c
runtime/src/iree/hal/drivers/local_sync/sync_device.c
runtime/src/iree/hal/drivers/local_task/task_device.c
runtime/src/iree/hal/drivers/metal/metal_device.m
runtime/src/iree/hal/drivers/vulkan/extensibility_util.h
runtime/src/iree/hal/drivers/vulkan/vulkan_device.cc

Adds device info struct and API to expose additional device metadata like device IDs and identifiers.
- Added identifier to `iree_hal_device_info_t` struct
->  Consolidated device identifier handling into the device info struct
- Added `iree_hal_device_info()` API to query device information
- Updated all HAL device implementations (CUDA, HIP, Metal, Vulkan, etc.) to populate and return device info
The device id is needed for dlpack export

Expose device info with internal device id of hal device

---

runtime/src/iree/hal/drivers/cuda/cuda_device.c

to get the runtime building again so i can update the submodule later, ci for this should run here: https://app.graphite.dev/github/pr/RooflineAI/roof-mlir/328/switch-submodule-and-test-for-memory-leak

fix runtime build

---

compiler/src/iree/compiler/Codegen/Dialect/Codegen/IR/IREECodegenAttrs.td

In order to add a completely new pipeline, we are required to add a new enum to the list of available codegen pipelines.
Up till now we have been using the pre-existing pipelines, but since we want to use our own custom codegen path we are now required to add it here.  
This most likely may have to happen for each custom target we add...

feat(CellarCuda): add pipeline codgen enum

---

compiler/src/iree/compiler/Codegen/Common/BlockDynamicDimensions.cpp
compiler/src/iree/compiler/Codegen/Common/test/block_dynamic_dims.mlir
compiler/src/iree/compiler/DispatchCreation/test/attention_fuse_by_expansion.mlir

This reverts commit 3bd685e7e858c524fee9b3c513c47be3f4e0227a, re-applying commit
d96d142fab6f059b44be38fb6ae1ea776097dd9a. To facilitate that, required changes
from LLVM are also integrated, along with an appropriate LIT test update.

Re-apply commit "[Codegen] Block dyn dims of parallel linalg.generic ops"

---

compiler/src/iree/compiler/DispatchCreation/BubbleUpExpandShapes.cpp
compiler/src/iree/compiler/DispatchCreation/SinkReshapes.cpp
compiler/src/iree/compiler/DispatchCreation/test/sink_reshapes.mlir

This reverts commit 567d9be440d1fb44d56248432c4b97ffdc5696f8.
This reapplies commit 272a7ffc88e1f7d924111d860d27a975cdca0869.
This is dependent on [llvm/llvm-project@4652b69](https://github.com/llvm/llvm-project/commit/4652b69).

Reapply "[Dispatch Creation] Enable more reshape movement (#20320)"

---

compiler/src/iree/compiler/Codegen/LLVMCPU/Passes.cpp

This reverts commit 0bc671eeec7935bbb20dd71cd99f2c5c7b8284f3.

Revert "workaround(iree): disable WG-context global writes verification for LLVMCPU"

---

compiler/plugins/input/TOSA/InputConversion/Passes.cpp
compiler/plugins/input/TOSA/InputConversion/Passes.h
compiler/plugins/input/TOSA/PluginRegistration.cpp

For our TOSA lowering, we do not need to validate against the
TOSA spec. Adding this option allows us to skip the valdiation
of the operation.

feat(TOSA); add disable profile validation option

---

runtime/bindings/python/BUILD.bazel

This one actually fixes the build issue that I encountered. Other issue we have is that our numpy version is not pinned and set to `>=2.0.0` which is fine, but I guess that was the root cause of the problem in the first place. I know that also taking care of bumping numpy versions etc. would also be a burden on the developer and is sort of unnecessary since it's not really like `torch` or `transformers` that _explicitly_ affect us, but still wanted to pull attention towards it as well.
The version I have on my local bazel cache in the workspace that I was using is `2.2.6` whereas the new workspace had `2.3.0`, which I think deleted those headers btw. The local one still works with the cached one, so you might actually need a clean workspace or clean your bazel cache to reproduce this. …

bugfix(build): fixes the runtime build issue roo-447

---

compiler/src/iree/compiler/Codegen/Common/MaterializeEncoding.cpp
compiler/src/iree/compiler/Codegen/Common/test/materialize_encoding_x86_64.mlir

This is step 2/3 of fixing the large vector sizes found compilation failure (roo-389). This PR adds the control function that would allow us to prevent folding pack/unpack operations into (transpose) ops that has multiple uses, e.g. the result is stored into a dispatch. 
To begin with, ending up with such dispatches is also problematic in means of memory footprint, but I guess fixing that would be a much more involved issue. So, this PR enables fusion by blocking inhibiting folding patterns. See IREE issue #20896 for more details.
The change I made, and therefore the test that would be changed is actually target-agnostic. Although generally, the pass that utilizes it isn't. So I just put it into one of them. If anyone has a better idea of where to put the test, please tell me :) …

feat(codegen): use control function to prevent fusion-inhibiting folding patterns

---

runtime/src/iree/hal/drivers/BUILD.bazel

Disable the target for now to duck the LLVM/Clang dependency for ROCM bitcode modules.
This is in the aftermath of [iree-org/iree@a123c8b](https://github.com/iree-org/iree/commit/a123c8b58aa9bc5cc4320f9046a933a037c11c6a), [iree-org/iree@bc5e67eb](https://github.com/iree-org/iree/commit/bc5e67eb0bf98418545792d1c3a024c5c368db4f).

fix(iree): disable obsolete AMDGPU HAL driver build
